apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../argocd-project-system
- ../argocd-application
- ../../cert-manager/argocd-application
- ../../cert-manager/default-tls-crt/argocd-application
- ../../kubernetes-dashboard/argocd-application
- ../../prometheus/argocd-application
- ../../registry-ui/argocd-application
- ../../traefik/argocd-application
