= k3d local cluster setup

This project is a collection of scripts, configurations, helm values and kustomizations to deploy a dev k3d cluster with some services pre-installed and exposed.

== Prerequsites
There are some prerequisistes necessary to run this project:

* DNS names of the form `.*k3d.localhost` must resolve to `localhost` (i.e. `127.0.0.1`)
* Software installed:
** link:https://www.docker.com/[`docker` (`www.docker.com`)], or a container runtime that is compatible with docker (and has an alias to the `docker` command), e.g. link:https://podman.io/[`podman` (`podman.io`)]
** link:https://kubernetes.io/docs/reference/kubectl/[`kubectl` cli (`kubernetes.io`)]
** link:https://helm.sh/[`helm` cli (`helm.sh`)]
** link:https://k3d.io/[`k3d` cli (`k3d.io`)]
** link:https://curl.se/[`curl` (`curl.se`)]
** link:https://www.openssl.org/[`openssl` (`www.openssl.org`)]
* An internet connection

== What is provided?

=== Scripts
Scripts to create, start, stop and delete the cluster can be found in directory `scripts`.

The connection-config to the cluster is written to the config-file in environment variable `K3D_KUBECONFIG`, defaulting to `${HOME}/.kube/config.k3d`.

The flow is as follows:

* to create a cluster, we call link:scripts/create-k3d-cluster.sh[`create-k3d-cluster.sh`]
* to stop (suspend) the cluster, we call link:scripts/stop-k3d-cluster.sh[`stop-k3d-cluster.sh`]. This will not delete anything.
* to start (resume) the cluster, we call link:scripts/start-k3d-cluster.sh[`start-k3d-cluster.sh`]. This can only start clusters, that were previously created and stopped.
* to delete a created cluster, we call link:scripts/delete-k3d-cluster.sh[`delete-k3d-cluster.sh`]. The image registries that were created are only stopped, not removed (i.e. we can still see them when running `docker ps -a`). If we subsequently create a new cluster, the same registry-containers (and volumes!) will be used, thus the images will be pulled from the mirrors, not from upstream.

[NOTE]
====
The first creation of a cluster will take a while since all images will be pulled. Subsequent cluster creations will be faster if the volume mounts for the registry and the mirrors are not deleted.
====

The scripts are not sensitive to the location they are called from; we can call them from everywhere. For convenience, we can link them to `${HOME}/.local/bin`:

.Link scripts to `${HOME}/.local/bin`
[source,bash]
----
cd /path/to/k3d-cluster/scripts
mapfile -t scripts < <(find . -name '*.sh')
for script in "${scripts[@]}"
do
  script_without_extension=$(basename "${script/.sh//}")
  ln -s "$(pwd)/${script}" "${HOME}/.local/bin/${script_without_extension}"
done
cd -
----

If `${HOME}/.local/bin` is on our `${PATH}`, then we can call the scripts (without the `.sh` extension) from everywhere.

=== Services
* link:https://argoproj.github.io/cd/[ArgoCD (`argoproj.github.io`)], available at link:https://argocd.k3d.localhost[`https://argocd.k3d.localhost`]
* link:https://github.com/kubernetes/dashboard[kubernetes-dashboad (`github.com`)], available at link:https://dashboard.k3d.localhost[`https://dashboard.k3d.localhos`]
* link:https://prometheus.io/[Prometheus (`https://prometheus.io`)] and link:https://grafana.com/[Grafana (`grafana.com`)], available at link:https://prometheus.k3d.localhost[`link:https://prometheus.k3d.localhost`] and link:https://grafana.k3d.localhost[`https://grafana.k3d.localhost`] respectively
** The credentials for grafana are `admin`/`prom-operator`
* link:https://doc.traefik.io/traefik/[traefik (`doc.traefik.io`)], the dashboard is available at link:https://traefik.k3d.localhost[`https://traefik.k3d.localhost`]
* link:https://cert-manager.io/[cert-manager (`cert-manager.io`)] for certificate-management
* link:https://docs.portainer.io/admin/environments/add/kubernetes/agent[portainer-agent (`docs.portainer.io`)] to connect the cluster to portainer

=== Image registry and mirrors
To improve the startup time of the cluster and make the cluster "offline-ready", we also deploy for image registries through the container runtime environment. Three registires are mirrors for `docker.com`, `quay.io`, and registry.k8s.io, one local registry to which we can push our images. The local registry is available on `localhost`, port `5000`. From within the cluster, the registry can be referenced through `local.registry.localhost:5000`.

For each of this registries, we also deploy a small web-ui. They are available at

* link:https://local.registry.k3d.localhost[`https://local.registry.k3d.localhost`]
* link:https://docker.registry.k3d.localhost[`https://docker.registry.k3d.localhos`]
* link:https://quay.registry.k3d.localhost[`https://quay.registry.k3d.localhost`]
* link:https://k8s-community.registry.k3d.localhost[`https://k8s-community.registry.k3d.localhost`]

=== TLS encryption
All endpoints are per default TLS-encrypted. For this, the `create-k3d-cluster`-script generates a self-signed certificate which is then used in conjunction with cert-manager and traefik for said TLs-encryptin. If we want, we can install the self-signed CA certificate in directory `cert-manager/certs/ca/ca.crt` in or browser and/or system.

=== GitOps everywhere
All services provided are installed through ArgoCD (even ArgoCD itself!).

== Contributors ✨

Thanks goes to these wonderful people (https://allcontributors.org/docs/en/emoji-key[emoji key]):

++++
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/turing85"><img src="https://avatars.githubusercontent.com/u/32584495?v=4?s=100" width="100px;" alt="Marco Bungart"/><br /><sub><b>Marco Bungart</b></sub></a><br /><a href="#code-turing85" title="Code">💻</a> <a href="#maintenance-turing85" title="Maintenance">🚧</a> <a href="#infra-turing85" title="Infrastructure (Hosting, Build-Tools, etc)">🚇</a></td>
      <td align="center" valign="top" width="14.28%"><a href="https://github.com/jbierboms"><img src="https://avatars.githubusercontent.com/u/11670769?v=4?s=100" width="100px;" alt="jbierboms"/><br /><sub><b>jbierboms</b></sub></a><br /><a href="#code-jbierboms" title="Code">💻</a></td>
    </tr>
  </tbody>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
++++

This project follows the https://github.com/all-contributors/all-contributors[all-contributors] specification. Contributions of any kind welcome!