= k3d local cluster setup

This project is a collection of scripts, configurations, helm values and kustomizations to deploy a dev k3d cluster with some services pre-installed and exposed.

== Prerequsites
There are some prerequisistes necessary to run this project:

* DNS names of the form `.*k3d.localhost` must resolve to `localhost` (i.e. `127.0.0.1`)
* Software installed:
** `docker`, or a container runtime that is compatible with docker (and has an alias to the `docker` command), e.g. podman
** `kubectl` cli
** `helm` cli
** `k3d` cli
** `curl`
** `openssl`
* An internet connection

== What is provided?

=== Scripts
Scripts to create, start, stop and delete the cluster can be found in directory `scripts`.

The connection-config to the cluster is written to the config-file in environment variable `K3D_KUBECONFIG`, defaulting to `${HOME}/.kube/config.k3d`

=== Services
* ArgoCD available at link:https://argocd.k3d.localhost[]
* kubernetes-dashboad, available at link:https://dashboard.k3d.localhost[]
* Grafana and Prometheus, available at link:https://grafana.k3d.localhost[] and link:https://prometheus.k3d.localhost[] respectively
** The credentials for grafana are `admin`/`prom-operator`
* traefik, the dashboard is available at link:https://traefik.k3d.localhost[]
* cert-manager
* portainer-agent to connect the cluster to portainer

=== Image registres and mirrors
To improve the startup time of the cluster and make the cluster "offline-ready", we also deploy three image registries through the container runtime environment. Two registires are mirrors for `docker.com` and `quay.io`, one local registry to which we can push our images. The local registry is available on `localhost`, port `5000`. From within the cluster, the registry can be referenced through `local.registry.localhost:5000`.

For each of this registries, we also deploy a small web-ui. They are available at

* link:https://local.registry.k3d.localhost[]
* link:https://docker.registry.k3d.localhost[]
* link:https://quay.registry.k3d.localhost[]

=== TLS encryption
All endpoints are per default TLS-encrypted. For this, the `create-k3d-cluster`-script generates a self-signed certificate which is then used in conjunction with cert-manager and traefik for said TLs-encryptin. If we want, we can install the self-signed CA certificate in directory `cert-manager/certs/ca/ca.crt` in or browser and/or system.

=== GitOps everywhere
All services provided are installed through ArgoCD (even ArgoCD itself!).