apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../argocd/application-templates/helm

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  patch: |
    - op: replace
      path: /metadata/name
      value: cert-manager
    - op: add
      path: /spec/destination/namespace
      value: cert-manager
    - op: add
      path: /spec/sources/0
      value:
        chart: cert-manager
        helm:
          releaseName: cert-manager
          valueFiles:
          - $values/cert-manager/helm-values.yml
        repoURL: https://charts.jetstack.io
        targetRevision: 1.15.3
