apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-ca
spec:
  ca:
    secretName: cluster-issuer-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls-crt
spec:
  secretName: default-tls-crt
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - digital signature
  - key encipherment
  dnsNames:
  - '*.k3d.localhost'
  issuerRef:
    name: cluster-issuer-ca
    kind: ClusterIssuer
