apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../argocd/application-templates/kustomize

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  patch: |
    - op: replace
      path: /metadata/name
      value: argocd-project-system
    - op: add
      path: /spec/destination/namespace
      value: argocd
    - op: add
      path: /spec/source/path
      value: argocd/argocd-project-system/
