apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: system
  sources:
  - chart: kube-prometheus-stack
    helm:
      releaseName: prometheus-operator
      valueFiles:
      - $values/prometheus/helm-values.yml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 54.2.2
  - ref: values
    repoURL: https://github.com/turing85/k3d-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
