apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../argocd/application-templates/helm

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  patch: |
    - op: replace
      path: /metadata/name
      value: traefik
    - op: add
      path: /spec/destination/namespace
      value: traefik
    - op: add
      path: /spec/sources/0
      value:
        chart: traefik
        helm:
          releaseName: traefik
          valueFiles:
          - $values/traefik/helm-values.yml
        repoURL: https://traefik.github.io/charts
        targetRevision: 25.0.0
