apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: system
  sources:
  - chart: traefik
    helm:
      releaseName: traefik
      valueFiles:
      - $values/traefik/helm-values.yml
    repoURL: https://traefik.github.io/charts
    targetRevision: 25.0.0
  - ref: values
    repoURL: https://github.com/turing85/k3d-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
