apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: system
  sources:
  - chart: cert-manager
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/cert-manager/helm/helm-values.yml
    repoURL: https://charts.jetstack.io
    targetRevision: 1.13.2
  - ref: values
    repoURL: https://github.com/turing85/k3d-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
