apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: PLACEHOLDER
spec:
  destination:
    server: https://kubernetes.default.svc
  project: system
  source:
    repoURL: https://github.com/turing85/k3d-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
