apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- ingress.yml

commonLabels:
  app.kubernetes.io/component: registry-ui
  app.kubernetes.io/name: registry-ui
