apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  project: system
  source:
    path: portainer
    repoURL: https://github.com/turing85/k3d-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

