apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: cluster-issuer-ca-cert
  files:
  - tls.crt=certs/inter/chain.crt
  - tls.key=certs/inter/inter.key
